version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/modules/attestation/snp"
      - "/modules/attestation/tdx"
      - "/integrations/cocos"
    schedule:
      interval: "weekly"
      day: "monday"
